version: '3'

services:
    brevets:
        build: brevets/.
        command: python -u flask_brevets.py -P $BREVETS_PORT
        ports:
            - "5000:$BREVETS_PORT"
        depends_on:
            - api
        environment:
            API_ADDR: api
            API_PORT: $API_PORT
            PORT: $BREVETS_PORT
            DEBUG: $DEBUG
    api:
        build: api/.
        command: python -u app.py -P $API_PORT
        ports:
            - "5001:$API_PORT"
        depends_on:
            - db
        environment:
            MONGODB_HOSTNAME: db
            MONGODB_PORT: ${MONGODB_PORT:-27017}
            PORT: $API_PORT
            DEBUG: $DEBUG
    db:
        image: mongo:latest
